# Generated by Django 5.2.10 on 2026-01-16 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('CAR_WASH', 'Oto Yikama'), ('TIRE_REPAIR', 'Lastik Tamir'), ('VEHICLE_REPAIR', 'Arac Tamir')], max_length=20)),
                ('status', models.CharField(choices=[('WAITING', 'Beklemede'), ('IN_PROGRESS', 'Islemde'), ('DONE', 'Teslim')], default='WAITING', max_length=20)),
                ('plate_text', models.CharField(blank=True, help_text='Arac kaydi yoksa plaka', max_length=20)),
                ('complaint', models.TextField(blank=True)),
                ('km', models.PositiveIntegerField(blank=True, null=True)),
                ('labor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, help_text='NAKIT/KART/HAVALE', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('is_part', models.BooleanField(default=False)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.workorder')),
            ],
        ),
    ]
