# Generated by Django 5.2.10 on 2026-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='complaint',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='NAKIT/KART/HAVALE', max_length=20),
        ),
    ]
