# Generated by Django 5.2.10 on 2026-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0003_workorder_finished_at_workorder_staff_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='estimate_labor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='estimate_parts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='estimate_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
