# Generated by Django 5.2.10 on 2026-01-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_workorderitem_estimate_labor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
