# Generated by Django 5.0 on 2026-01-28 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_workorder_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='worker_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='worker_finished_by_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='workorder',
            name='worker_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorder',
            name='worker_services',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='kind',
            field=models.CharField(choices=[('CAR_WASH', 'Oto Yıkama'), ('TIRE_REPAIR', 'Lastik Tamir'), ('VEHICLE_REPAIR', 'Araç Tamir')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='plate_text',
            field=models.CharField(blank=True, help_text='Araç kaydı yoksa plaka', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Beklemede'), ('IN_PROGRESS', 'İşlemde'), ('DONE', 'Teslim')], default='WAITING', max_length=20),
        ),
    ]
