# Generated by Django 5.2.10 on 2026-01-22 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('workorders', '0003_workorder_finished_at_workorder_staff_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=50)),
                ('barcode', models.CharField(blank=True, default='', max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('brand', models.CharField(blank=True, default='', max_length=80)),
                ('unit', models.CharField(blank=True, default='adet', max_length=20)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('IN', 'Giriş (+)'), ('OUT', 'Çıkış (-)')], max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.part')),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='workorders.workorder')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.part')),
            ],
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['branch', 'name'], name='inventory_p_branch__887e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['branch', 'barcode'], name='inventory_p_branch__7ae944_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('branch', 'sku')},
        ),
    ]
