# Generated by Django 5.2.10 on 2026-01-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
