# Generated by Django 5.2.10 on 2026-01-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0002_part_min_stock'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['branch', 'sku'], name='inventory_p_branch__925a69_idx'),
        ),
    ]
