# Generated by Django 5.2.10 on 2026-01-26 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappclicklog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappclicklog',
            name='message_type',
            field=models.CharField(choices=[('OPEN', 'Tek Tık Aç'), ('CAMPAIGN', 'Toplu Mesaj')], default='OPEN', max_length=20),
        ),
    ]
