# Generated by Django 5.2.10 on 2026-01-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('customers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TireHotelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_text', models.CharField(blank=True, max_length=20)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('size', models.CharField(blank=True, help_text='Orn: 205/55R16', max_length=40)),
                ('season', models.CharField(choices=[('SUMMER', 'Yazlik'), ('WINTER', 'Kislik')], default='WINTER', max_length=10)),
                ('qty', models.PositiveIntegerField(default=4)),
                ('rack_code', models.CharField(help_text='Raf kodu: orn R3', max_length=10)),
                ('slot_code', models.CharField(help_text='Goz kodu: orn G12', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tirehotel')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.vehicle')),
            ],
        ),
    ]
